library(DESeq2)

# Gene-count files generated by HTSeq
files <- c(
    "output/gene_counts_SRR427120.txt",
    "output/gene_counts_SRR427121.txt",
    "output/gene_counts_SRR427122.txt",
    "output/gene_counts_SRR427126.txt",
    "output/gene_counts_SRR427127.txt",
    "output/gene_counts_SRR427128.txt"
)

counts_list <- lapply(
    files,
    function(x) read.table(x, header = FALSE, row.names = 1)
)

count_matrix <- do.call(cbind, counts_list)

colnames(count_matrix) <- c(
    "SRR427120",
    "SRR427121",
    "SRR427122",
    "SRR427126",
    "SRR427127",
    "SRR427128"
)

write.csv(count_matrix, "output/count_matrix.csv")

counts <- read.csv(
    "output/count_matrix.csv",
    row.names = 1,
    check.names = FALSE
)

sample_info <- data.frame(
    condition = factor(
        c(
            "control", "control", "control",
            "ampicillin", "ampicillin", "ampicillin"
        )
    )
)

rownames(sample_info) <- colnames(counts)

dds <- DESeqDataSetFromMatrix(
    countData = counts,
    colData = sample_info,
    design = ~ condition
)

dds <- DESeq(dds)

res <- results(dds)

summary(res)

write.csv(
    as.data.frame(res),
    "output/deseq2_results.csv"
)

png(
    "figures/volcano_plot.png",
    width = 1200,
    height = 900
)

plot(
    res$log2FoldChange,
    -log10(res$pvalue),
    pch = 20,
    main = "Ampicillin vs Control",
    xlab = "Log2 Fold Change",
    ylab = "-Log10(p-value)"
)

abline(v = c(-1, 1), lty = 2)
abline(h = -log10(0.05), lty = 2)

dev.off()
